// const data = [{makeName:}];

// export default data;

export const mockedCarData = {
  makeName: "BMW",
  version: [
    "X1",
    "7 Series",
    "2 Series Gran Coupe",
    "X7",
    "3 Series Gran Limousine",
    "Z4",
    "M4 Competition",
    "M340i",
    "M8",
    "6 Series GT",
    "X5",
    "XM",
    "M2",
    "X3",
    "X4 M40i",
    "i7",
    "i4",
    "iX1",
    "X3 M40i",
    "X5 M",
    "iX",
  ],
};

const data = [
  {
    modelId: 1729,
    modelName: "Creta",
    maskingName: "creta",
    rootId: "382",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "01/16/2024 00:00:00",
    discontinuationDate: "",
    rootName: "Creta",
    status: "New",
    imagePath:
      "/n/cw/ec/106815/creta-exterior-right-front-three-quarter-4.png?isig=0",
    versionId: 9371,
  },
  {
    modelId: 1264,
    modelName: "Scorpio N",
    maskingName: "scorpio-n",
    rootId: "266",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "06/27/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Scorpio",
    status: "New",
    imagePath:
      "/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-75.jpeg?isig=0",
    versionId: 12941,
  },
  {
    modelId: 2033,
    modelName: "Fronx",
    maskingName: "fronx",
    rootId: "775",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "04/24/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Fronx",
    status: "New",
    imagePath:
      "/n/cw/ec/130591/fronx-exterior-right-front-three-quarter-109.jpeg?isig=0",
    versionId: 11543,
  },
  {
    modelId: 1260,
    modelName: "Thar",
    maskingName: "thar",
    rootId: "174",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "10/02/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Thar",
    status: "New",
    imagePath:
      "/n/cw/ec/40087/thar-exterior-right-front-three-quarter-35.jpeg?isig=0",
    versionId: 13269,
  },
  {
    modelId: 1238,
    modelName: "Punch",
    maskingName: "punch",
    rootId: "529",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "10/18/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Punch",
    status: "New",
    imagePath:
      "/n/cw/ec/39015/punch-exterior-right-front-three-quarter-54.jpeg?isig=0",
    versionId: 13859,
  },
  {
    modelId: 1739,
    modelName: "Brezza",
    maskingName: "brezza",
    rootId: "423",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "06/30/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Vitara Brezza",
    status: "New",
    imagePath:
      "/n/cw/ec/107543/brezza-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 13447,
  },
  {
    modelId: 1875,
    modelName: "Grand Vitara",
    maskingName: "grand-vitara",
    rootId: "703",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "09/26/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Grand Vitara",
    status: "New",
    imagePath:
      "/n/cw/ec/123185/grand-vitara-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 13663,
  },
  {
    modelId: 2333,
    modelName: "Nexon",
    maskingName: "nexon",
    rootId: "378",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "09/14/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Nexon",
    status: "New",
    imagePath:
      "/n/cw/ec/141867/nexon-exterior-right-front-three-quarter-71.jpeg?isig=0",
    versionId: 14823,
  },
  {
    modelId: 1985,
    modelName: "Scorpio",
    maskingName: "scorpio",
    rootId: "266",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "08/19/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Scorpio",
    status: "New",
    imagePath:
      "/n/cw/ec/128413/scorpio-exterior-right-front-three-quarter-47.jpeg?isig=0",
    versionId: 13001,
  },
  {
    modelId: 2437,
    modelName: "Exter",
    maskingName: "exter",
    rootId: "821",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "07/10/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Exter",
    status: "New",
    imagePath:
      "/n/cw/ec/144851/exter-exterior-right-front-three-quarter-29.jpeg?isig=0",
    versionId: 14051,
  },
  {
    modelId: 1290,
    modelName: "XUV700",
    maskingName: "xuv700",
    rootId: "617",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "09/30/2021 00:00:00",
    discontinuationDate: "",
    rootName: "XUV700",
    status: "New",
    imagePath:
      "/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 16215,
  },
  {
    modelId: 2241,
    modelName: "Harrier",
    maskingName: "harrier",
    rootId: "501",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "10/17/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Harrier",
    status: "New",
    imagePath:
      "/n/cw/ec/139139/harrier-facelift-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 12015,
  },
  {
    modelId: 2495,
    modelName: "Punch EV",
    maskingName: "punch-ev",
    rootId: "2523",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "01/17/2024 00:00:00",
    discontinuationDate: "",
    rootName: "Punch EV",
    status: "New",
    imagePath:
      "/n/cw/ec/148309/punch-ev-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 16089,
  },
  {
    modelId: 2317,
    modelName: "Sonet",
    maskingName: "sonet",
    rootId: "546",
    makeId: 70,
    makeName: "Kia",
    makeMaskingName: "kia",
    launchedOn: "01/12/2024 00:00:00",
    discontinuationDate: "",
    rootName: "Sonet",
    status: "New",
    imagePath:
      "/n/cw/ec/141383/sonet-facelift-exterior-right-front-three-quarter-8.jpeg?isig=0",
    versionId: 15925,
  },
  {
    modelId: 1887,
    modelName: "Urban Cruiser Hyryder",
    maskingName: "urban-cruiser-hyryder",
    rootId: "721",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "09/09/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Urban Cruiser Hyryder",
    status: "New",
    imagePath:
      "/n/cw/ec/124027/urban-cruiser-hyryder-exterior-right-front-three-quarter-72.jpeg?isig=0",
    versionId: 14795,
  },
  {
    modelId: 1839,
    modelName: "Ertiga",
    maskingName: "ertiga",
    rootId: "117",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "04/15/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Ertiga",
    status: "New",
    imagePath:
      "/n/cw/ec/115777/ertiga-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 13545,
  },
  {
    modelId: 2303,
    modelName: "Innova Crysta",
    maskingName: "innova-crysta",
    rootId: "835",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "03/15/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Innova Crysta",
    status: "New",
    imagePath:
      "/n/cw/ec/140809/innova-crysta-exterior-right-front-three-quarter-2.png?isig=0",
    versionId: 11675,
  },
  {
    modelId: 1963,
    modelName: "Alto K10",
    maskingName: "alto-k10",
    rootId: "530",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "08/18/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Alto K10",
    status: "New",
    imagePath:
      "/n/cw/ec/127563/alto-k10-exterior-right-front-three-quarter-58.jpeg?isig=0",
    versionId: 13415,
  },
  {
    modelId: 1417,
    modelName: "Swift",
    maskingName: "swift",
    rootId: "288",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "02/24/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Swift",
    status: "New",
    imagePath:
      "/n/cw/ec/54399/swift-exterior-right-front-three-quarter-64.jpeg?isig=0",
    versionId: 13601,
  },
  {
    modelId: 2309,
    modelName: "Venue",
    maskingName: "venue",
    rootId: "515",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "02/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Venue",
    status: "New",
    imagePath:
      "/n/cw/ec/141113/venue-exterior-right-front-three-quarter-16.jpeg?isig=0",
    versionId: 15787,
  },
  {
    modelId: 2141,
    modelName: "Seltos",
    maskingName: "seltos",
    rootId: "504",
    makeId: 70,
    makeName: "Kia",
    makeMaskingName: "kia",
    launchedOn: "07/21/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Seltos",
    status: "New",
    imagePath:
      "/n/cw/ec/135051/seltos-exterior-right-front-three-quarter-31.jpeg?isig=0",
    versionId: 14421,
  },
  {
    modelId: 1089,
    modelName: "XUV300",
    maskingName: "xuv300",
    rootId: "469",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "02/14/2019 00:00:00",
    discontinuationDate: "",
    rootName: "XUV300",
    status: "New",
    imagePath:
      "/n/cw/ec/26918/xuv300-exterior-right-front-three-quarter-148709.jpeg?isig=0",
    versionId: 14679,
  },
  {
    modelId: 1250,
    modelName: "Tiago",
    maskingName: "tiago",
    rootId: "377",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "01/22/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Tiago",
    status: "New",
    imagePath:
      "/n/cw/ec/39345/tiago-exterior-right-front-three-quarter-27.jpeg?isig=0",
    versionId: 13777,
  },
  {
    modelId: 2031,
    modelName: "Hector",
    maskingName: "hector",
    rootId: "521",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "01/11/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Hector",
    status: "New",
    imagePath:
      "/n/cw/ec/130583/hector-exterior-right-front-three-quarter-75.jpeg?isig=0",
    versionId: 14119,
  },
  {
    modelId: 1811,
    modelName: "Wagon R",
    maskingName: "wagon-r",
    rootId: "313",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "02/25/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Wagon R",
    status: "New",
    imagePath:
      "/n/cw/ec/112947/wagon-r-2022-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13623,
  },
  {
    modelId: 2219,
    modelName: "Safari",
    maskingName: "safari",
    rootId: "257",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "10/17/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Safari",
    status: "New",
    imagePath:
      "/n/cw/ec/138895/safari-facelift-exterior-right-front-three-quarter-39.jpeg?isig=0",
    versionId: 12045,
  },
  {
    modelId: 1633,
    modelName: "Baleno",
    maskingName: "baleno",
    rootId: "48",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "02/23/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Baleno",
    status: "New",
    imagePath:
      "/n/cw/ec/102663/baleno-exterior-right-front-three-quarter-66.jpeg?isig=0",
    versionId: 13429,
  },
  {
    modelId: 1151,
    modelName: "Altroz",
    maskingName: "altroz",
    rootId: "495",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "01/22/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Altroz",
    status: "New",
    imagePath:
      "/n/cw/ec/32597/altroz-exterior-right-front-three-quarter-80.jpeg?isig=0",
    versionId: 13705,
  },
  {
    modelId: 2521,
    modelName: "i20",
    maskingName: "i20",
    rootId: "476",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "09/08/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Elite i20",
    status: "New",
    imagePath:
      "/n/cw/ec/150603/i20-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 14925,
  },
  {
    modelId: 1821,
    modelName: "Innova Hycross",
    maskingName: "innova-hycross",
    rootId: "751",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "12/28/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Innova Hycross",
    status: "New",
    imagePath:
      "/n/cw/ec/115025/innova-hycross-exterior-right-front-three-quarter-73.jpeg?isig=0",
    versionId: 11305,
  },
  {
    modelId: 2063,
    modelName: "Bolero",
    maskingName: "bolero",
    rootId: "53",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "09/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Bolero",
    status: "New",
    imagePath:
      "/n/cw/ec/131179/bolero-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 12827,
  },
  {
    modelId: 2177,
    modelName: "Grand i10 Nios",
    maskingName: "grand-i10-nios",
    rootId: "549",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "01/20/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Grand i10 NIOS",
    status: "New",
    imagePath:
      "/n/cw/ec/136183/grand-i10-nios-exterior-right-front-three-quarter-15.jpeg?isig=0",
    versionId: 15767,
  },
  {
    modelId: 1385,
    modelName: "Astor",
    maskingName: "astor",
    rootId: "605",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "10/11/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Astor",
    status: "New",
    imagePath:
      "/n/cw/ec/51940/astor-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 16163,
  },
  {
    modelId: 1863,
    modelName: "Verna",
    maskingName: "verna",
    rootId: "307",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "03/21/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Verna",
    status: "New",
    imagePath:
      "/n/cw/ec/121943/verna-exterior-right-front-three-quarter-101.jpeg?isig=0",
    versionId: 10937,
  },
  {
    modelId: 1807,
    modelName: "Glanza",
    maskingName: "glanza",
    rootId: "538",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "03/15/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Glanza",
    status: "New",
    imagePath:
      "/n/cw/ec/112839/glanza-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 14467,
  },
  {
    modelId: 1707,
    modelName: "Rumion",
    maskingName: "rumion",
    rootId: "659",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "08/28/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Rumion",
    status: "New",
    imagePath:
      "/n/cw/ec/105799/rumion-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 14669,
  },
  {
    modelId: 1329,
    modelName: "Magnite",
    maskingName: "magnite",
    rootId: "581",
    makeId: 21,
    makeName: "Nissan",
    makeMaskingName: "nissan",
    launchedOn: "12/02/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Magnite",
    status: "New",
    imagePath:
      "/n/cw/ec/45795/magnite-exterior-right-front-three-quarter-10.jpeg?isig=0",
    versionId: 12783,
  },
  {
    modelId: 1327,
    modelName: "Dzire",
    maskingName: "dzire",
    rootId: "481",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "03/20/2020 00:00:00",
    discontinuationDate: "",
    rootName: "DZire",
    status: "New",
    imagePath:
      "/n/cw/ec/45691/dzire-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13501,
  },
  {
    modelId: 1309,
    modelName: "Fortuner",
    maskingName: "fortuner",
    rootId: "135",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "01/06/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Fortuner",
    status: "New",
    imagePath:
      "/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-20.jpeg?isig=0",
    versionId: 7715,
  },
  {
    modelId: 2313,
    modelName: "Kwid",
    maskingName: "kwid",
    rootId: "395",
    makeId: 45,
    makeName: "Renault",
    makeMaskingName: "renault",
    launchedOn: "02/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Kwid",
    status: "New",
    imagePath:
      "/n/cw/ec/141125/kwid-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 16181,
  },
  {
    modelId: 2545,
    modelName: "Range Rover Velar",
    maskingName: "range-rover-velar",
    rootId: "473",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "07/24/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Range Rover Velar",
    status: "New",
    imagePath:
      "/n/cw/ec/153319/range-rover-velar-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 14521,
  },
  {
    modelId: 1923,
    modelName: "Comet EV",
    maskingName: "comet-ev",
    rootId: "711",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "04/26/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Comet EV",
    status: "New",
    imagePath:
      "/n/cw/ec/125193/comet-ev-exterior-right-side-view-23.jpeg?isig=0",
    versionId: 11395,
  },
  {
    modelId: 2349,
    modelName: "Elevate",
    maskingName: "elevate",
    rootId: "539",
    makeId: 7,
    makeName: "Honda",
    makeMaskingName: "honda",
    launchedOn: "09/04/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Elevate",
    status: "New",
    imagePath:
      "/n/cw/ec/142515/elevate-exterior-right-front-three-quarter-21.jpeg?isig=0",
    versionId: 14397,
  },
  {
    modelId: 2065,
    modelName: "Bolero Neo",
    maskingName: "bolero-neo",
    rootId: "53",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "09/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Bolero",
    status: "New",
    imagePath:
      "/n/cw/ec/131181/bolero-neo-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 12833,
  },
  {
    modelId: 2413,
    modelName: "Carens",
    maskingName: "carens",
    rootId: "665",
    makeId: 70,
    makeName: "Kia",
    makeMaskingName: "kia",
    launchedOn: "03/15/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Carens",
    status: "New",
    imagePath:
      "/n/cw/ec/144163/carens-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 12393,
  },
  {
    modelId: 2431,
    modelName: "Virtus",
    maskingName: "virtus",
    rootId: "647",
    makeId: 20,
    makeName: "Volkswagen",
    makeMaskingName: "volkswagen",
    launchedOn: "03/22/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Virtus",
    status: "New",
    imagePath:
      "/n/cw/ec/144681/virtus-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 12545,
  },
  {
    modelId: 2439,
    modelName: "Slavia",
    maskingName: "slavia",
    rootId: "663",
    makeId: 15,
    makeName: "Skoda",
    makeMaskingName: "skoda",
    launchedOn: "03/28/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Slavia",
    status: "New",
    imagePath:
      "/n/cw/ec/144999/slavia-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 12655,
  },
  {
    modelId: 2311,
    modelName: "Triber",
    maskingName: "triber",
    rootId: "534",
    makeId: 45,
    makeName: "Renault",
    makeMaskingName: "renault",
    launchedOn: "02/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Triber",
    status: "New",
    imagePath:
      "/n/cw/ec/141119/triber-exterior-right-front-three-quarter-8.jpeg?isig=0",
    versionId: 16095,
  },
  {
    modelId: 1323,
    modelName: "Jimny",
    maskingName: "jimny",
    rootId: "578",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "06/07/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Jimny",
    status: "New",
    imagePath:
      "/n/cw/ec/45299/jimny-exterior-right-front-three-quarter-27.jpeg?isig=0",
    versionId: 10707,
  },
  {
    modelId: 1332,
    modelName: "Amaze",
    maskingName: "amaze",
    rootId: "36",
    makeId: 7,
    makeName: "Honda",
    makeMaskingName: "honda",
    launchedOn: "08/18/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Amaze",
    status: "New",
    imagePath:
      "/n/cw/ec/45951/amaze-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 12759,
  },
  {
    modelId: 1937,
    modelName: "S-Presso",
    maskingName: "s-presso",
    rootId: "542",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "07/18/2022 00:00:00",
    discontinuationDate: "",
    rootName: "S-Presso",
    status: "New",
    imagePath:
      "/n/cw/ec/126463/s-presso-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13585,
  },
  {
    modelId: 2441,
    modelName: "Kushaq",
    maskingName: "kushaq",
    rootId: "558",
    makeId: 15,
    makeName: "Skoda",
    makeMaskingName: "skoda",
    launchedOn: "03/28/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Kushaq",
    status: "New",
    imagePath:
      "/n/cw/ec/145021/kushaq-exterior-right-front-three-quarter-12.jpeg?isig=0",
    versionId: 12683,
  },
  {
    modelId: 1411,
    modelName: "Celerio",
    maskingName: "celerio",
    rootId: "68",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "11/10/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Celerio",
    status: "New",
    imagePath:
      "/n/cw/ec/53695/celerio-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 13477,
  },
  {
    modelId: 1665,
    modelName: "C3",
    maskingName: "c3",
    rootId: "653",
    makeId: 74,
    makeName: "Citroen",
    makeMaskingName: "citroen",
    launchedOn: "07/20/2022 00:00:00",
    discontinuationDate: "",
    rootName: "C3",
    status: "New",
    imagePath:
      "/n/cw/ec/103611/exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13191,
  },
  {
    modelId: 2239,
    modelName: "Aura",
    maskingName: "aura",
    rootId: "547",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "01/23/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Aura",
    status: "New",
    imagePath:
      "/n/cw/ec/139133/aura-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 15663,
  },
  {
    modelId: 2131,
    modelName: "City",
    maskingName: "city",
    rootId: "74",
    makeId: 7,
    makeName: "Honda",
    makeMaskingName: "honda",
    launchedOn: "03/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "City",
    status: "New",
    imagePath:
      "/n/cw/ec/134287/city-exterior-right-front-three-quarter-76.jpeg?isig=0",
    versionId: 12301,
  },
  {
    modelId: 2331,
    modelName: "Kiger",
    maskingName: "kiger",
    rootId: "557",
    makeId: 45,
    makeName: "Renault",
    makeMaskingName: "renault",
    launchedOn: "02/10/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Kiger",
    status: "New",
    imagePath:
      "/n/cw/ec/141857/kiger-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 16111,
  },
  {
    modelId: 2735,
    modelName: "GLA",
    maskingName: "gla",
    rootId: "372",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "01/31/2024 00:00:00",
    discontinuationDate: "",
    rootName: "GLA",
    status: "New",
    imagePath:
      "/n/cw/ec/169159/gla-facelift-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 16355,
  },
  {
    modelId: 1421,
    modelName: "Defender",
    maskingName: "defender",
    rootId: "104",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "03/12/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Defender",
    status: "New",
    imagePath:
      "/n/cw/ec/55215/defender-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13185,
  },
  {
    modelId: 2433,
    modelName: "Taigun",
    maskingName: "taigun",
    rootId: "568",
    makeId: 20,
    makeName: "Volkswagen",
    makeMaskingName: "volkswagen",
    launchedOn: "03/23/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Taigun",
    status: "New",
    imagePath:
      "/n/cw/ec/144689/taigun-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 12557,
  },
  {
    modelId: 1230,
    modelName: "Range Rover Evoque",
    maskingName: "range-rover-evoque",
    rootId: "124",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "01/30/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Evoque",
    status: "New",
    imagePath:
      "/n/cw/ec/37721/range-rover-evoque-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 16351,
  },
  {
    modelId: 1277,
    modelName: "Tigor",
    maskingName: "tigor",
    rootId: "472",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "01/22/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Tigor",
    status: "New",
    imagePath:
      "/n/cw/ec/41160/tigor-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13815,
  },
  {
    modelId: 1835,
    modelName: "XL6",
    maskingName: "xl6",
    rootId: "550",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "04/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XL6",
    status: "New",
    imagePath:
      "/n/cw/ec/115601/2022-xl6-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13645,
  },
  {
    modelId: 2525,
    modelName: "G-Class",
    maskingName: "g-class",
    rootId: "144",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "06/08/2023 00:00:00",
    discontinuationDate: "",
    rootName: "G-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/150621/g-class-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 14371,
  },
  {
    modelId: 2271,
    modelName: "Land Cruiser",
    maskingName: "land-cruiser",
    rootId: "183",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "12/22/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Land Cruiser",
    status: "New",
    imagePath:
      "/n/cw/ec/139739/land-cruiser-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 11951,
  },
  {
    modelId: 2249,
    modelName: "Hector Plus",
    maskingName: "hector-plus",
    rootId: "571",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "01/11/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Hector Plus",
    status: "New",
    imagePath:
      "/n/cw/ec/139315/hector-plus-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14277,
  },
  {
    modelId: 1343,
    modelName: "Compass",
    maskingName: "compass",
    rootId: "456",
    makeId: 43,
    makeName: "Jeep",
    makeMaskingName: "jeep",
    launchedOn: "01/27/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Compass",
    status: "New",
    imagePath:
      "/n/cw/ec/47051/compass-exterior-right-front-three-quarter-74.jpeg?isig=0",
    versionId: 12921,
  },
  {
    modelId: 2503,
    modelName: "Nexon EV",
    maskingName: "nexon-ev",
    rootId: "580",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "09/14/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Nexon EV",
    status: "New",
    imagePath:
      "/n/cw/ec/149123/nexon-ev-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 14895,
  },
  {
    modelId: 2301,
    modelName: "X1",
    maskingName: "x1",
    rootId: "315",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/28/2023 00:00:00",
    discontinuationDate: "",
    rootName: "X1",
    status: "New",
    imagePath:
      "/n/cw/ec/140591/x1-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 13849,
  },
  {
    modelId: 2341,
    modelName: "C3 Aircross",
    maskingName: "c3-aircross",
    rootId: "809",
    makeId: 74,
    makeName: "Citroen",
    makeMaskingName: "citroen",
    launchedOn: "09/16/2023 00:00:00",
    discontinuationDate: "",
    rootName: "C3 Aircross",
    status: "New",
    imagePath:
      "/n/cw/ec/142375/c3-aircross-exterior-right-front-three-quarter-31.jpeg?isig=0",
    versionId: 14571,
  },
  {
    modelId: 1743,
    modelName: "Range Rover",
    maskingName: "range-rover",
    rootId: "239",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "07/11/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Range Rover",
    status: "New",
    imagePath:
      "/n/cw/ec/107719/range-rover-exterior-right-front-three-quarter-46.jpeg?isig=0",
    versionId: 13063,
  },
  {
    modelId: 2107,
    modelName: "7 Series",
    maskingName: "7-series",
    rootId: "23",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/07/2023 00:00:00",
    discontinuationDate: "",
    rootName: "7-Series",
    status: "New",
    imagePath:
      "/n/cw/ec/132513/7-series-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15957,
  },
  {
    modelId: 1188,
    modelName: "Cooper",
    maskingName: "cooper",
    rootId: "87",
    makeId: 51,
    makeName: "MINI",
    makeMaskingName: "mini",
    launchedOn: "05/24/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Cooper",
    status: "New",
    imagePath:
      "/n/cw/ec/34560/cooper-exterior-right-front-three-quarter-2.jpeg",
    versionId: 10043,
  },
  {
    modelId: 1266,
    modelName: "Tiago EV",
    maskingName: "tiago-ev",
    rootId: "701",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "09/28/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Tiago EV",
    status: "New",
    imagePath:
      "/n/cw/ec/40453/tiago-ev-exterior-right-front-three-quarter-11.jpeg?isig=0",
    versionId: 9161,
  },
  {
    modelId: 2509,
    modelName: "A-Class Limousine",
    maskingName: "a-class-limousine",
    rootId: "837",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "05/24/2023 00:00:00",
    discontinuationDate: "",
    rootName: "A-Class Limousine",
    status: "New",
    imagePath:
      "/n/cw/ec/149525/a-class-limousine-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 15631,
  },
  {
    modelId: 2155,
    modelName: "Eeco",
    maskingName: "eeco",
    rootId: "112",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "11/22/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Eeco",
    status: "New",
    imagePath:
      "/n/cw/ec/135523/eeco-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13493,
  },
  {
    modelId: 1321,
    modelName: "XUV400",
    maskingName: "xuv400",
    rootId: "576",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "01/16/2023 00:00:00",
    discontinuationDate: "",
    rootName: "XUV400",
    status: "New",
    imagePath:
      "/n/cw/ec/45278/xuv400-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 16153,
  },
  {
    modelId: 1419,
    modelName: "Wrangler",
    maskingName: "wrangler",
    rootId: "444",
    makeId: 43,
    makeName: "Jeep",
    makeMaskingName: "jeep",
    launchedOn: "03/17/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Wrangler",
    status: "New",
    imagePath:
      "/n/cw/ec/54437/wrangler-exterior-right-front-three-quarter-52.jpeg?isig=0",
    versionId: 8099,
  },
  {
    modelId: 2191,
    modelName: "Fortuner Legender",
    maskingName: "fortuner-legender",
    rootId: "135",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "01/06/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Fortuner",
    status: "New",
    imagePath:
      "/n/cw/ec/137767/fortuner-legender-exterior-right-front-three-quarter-3.png?isig=0",
    versionId: 11369,
  },
  {
    modelId: 2351,
    modelName: "Alcazar",
    maskingName: "alcazar",
    rootId: "615",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "02/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Alcazar",
    status: "New",
    imagePath:
      "/n/cw/ec/142523/alcazar-exterior-right-front-three-quarter-11.jpeg?isig=0",
    versionId: 15821,
  },
  {
    modelId: 1061,
    modelName: "Ciaz",
    maskingName: "ciaz",
    rootId: "373",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "08/20/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Ciaz",
    status: "New",
    imagePath:
      "/n/cw/ec/48542/ciaz-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13525,
  },
  {
    modelId: 2087,
    modelName: "XUV300 TurboSport",
    maskingName: "xuv300-turbosport",
    rootId: "469",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "10/07/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XUV300",
    status: "New",
    imagePath:
      "/n/cw/ec/131907/xuv300-turbosport-exterior-right-front-three-quarter-9.jpeg?isig=0",
    versionId: 14681,
  },
  {
    modelId: 1357,
    modelName: "2 Series Gran Coupe",
    maskingName: "2-series-gran-coupe",
    rootId: "592",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "10/15/2020 00:00:00",
    discontinuationDate: "",
    rootName: "2 Series Gran Coupe",
    status: "New",
    imagePath:
      "/n/cw/ec/48034/2-series-gran-coupe-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13351,
  },
  {
    modelId: 1384,
    modelName: "A4",
    maskingName: "a4",
    rootId: "26",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "01/05/2021 00:00:00",
    discontinuationDate: "",
    rootName: "A4",
    status: "New",
    imagePath: "/n/cw/ec/51909/a4-exterior-right-front-three-quarter-2.jpeg",
    versionId: 9201,
  },
  {
    modelId: 1783,
    modelName: "Camry",
    maskingName: "camry",
    rootId: "58",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "01/12/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Camry",
    status: "New",
    imagePath:
      "/n/cw/ec/110233/camry-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 9313,
  },
  {
    modelId: 1825,
    modelName: "Maybach S-Class",
    maskingName: "maybach-s-class",
    rootId: "839",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "03/31/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Maybach S-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/115149/maybach-s-class-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15707,
  },
  {
    modelId: 1339,
    modelName: "F-Type",
    maskingName: "f-type",
    rootId: "140",
    makeId: 44,
    makeName: "Jaguar",
    makeMaskingName: "jaguar",
    launchedOn: "02/12/2020 00:00:00",
    discontinuationDate: "",
    rootName: "F-type",
    status: "New",
    imagePath:
      "/n/cw/ec/46994/f-type-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15571,
  },
  {
    modelId: 1773,
    modelName: "Hilux",
    maskingName: "hilux",
    rootId: "681",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "03/31/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Hilux",
    status: "New",
    imagePath:
      "/n/cw/ec/109265/hilux-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 9363,
  },
  {
    modelId: 2491,
    modelName: "Invicto",
    maskingName: "invicto",
    rootId: "829",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "07/05/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Invicto",
    status: "New",
    imagePath:
      "/n/cw/ec/147201/invicto-exterior-right-front-three-quarter-69.jpeg?isig=0",
    versionId: 14361,
  },
  {
    modelId: 2059,
    modelName: "S90",
    maskingName: "s90",
    rootId: "434",
    makeId: 37,
    makeName: "Volvo",
    makeMaskingName: "volvo",
    launchedOn: "09/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "S90",
    status: "New",
    imagePath:
      "/n/cw/ec/131145/s90-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 15413,
  },
  {
    modelId: 1845,
    modelName: "C-Class",
    maskingName: "c-class",
    rootId: "65",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "05/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "C-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/116201/c-class-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15657,
  },
  {
    modelId: 2363,
    modelName: "Ignis",
    maskingName: "ignis",
    rootId: "428",
    makeId: 10,
    makeName: "Maruti Suzuki",
    makeMaskingName: "maruti-suzuki",
    launchedOn: "02/26/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Ignis",
    status: "New",
    imagePath:
      "/n/cw/ec/142921/ignis-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13563,
  },
  {
    modelId: 2179,
    modelName: "X7",
    maskingName: "x7",
    rootId: "474",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/17/2023 00:00:00",
    discontinuationDate: "",
    rootName: "X7",
    status: "New",
    imagePath:
      "/n/cw/ec/136217/x7-exterior-right-front-three-quarter-8.jpeg?isig=0",
    versionId: 13387,
  },
  {
    modelId: 2245,
    modelName: "3 Series Gran Limousine",
    maskingName: "3-series-gran-limousine",
    rootId: "14",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/10/2023 00:00:00",
    discontinuationDate: "",
    rootName: "3-Series",
    status: "New",
    imagePath:
      "/n/cw/ec/139177/3-series-gran-limousine-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13355,
  },
  {
    modelId: 1955,
    modelName: "Discovery Sport",
    maskingName: "discovery-sport",
    rootId: "407",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "07/29/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Discovery Sport",
    status: "New",
    imagePath:
      "/n/cw/ec/127321/discovery-sport-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 16275,
  },
  {
    modelId: 2501,
    modelName: "Z4",
    maskingName: "z4",
    rootId: "331",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "05/25/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Z4",
    status: "New",
    imagePath:
      "/n/cw/ec/149075/z4-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14193,
  },
  {
    modelId: 2005,
    modelName: "Gloster",
    maskingName: "gloster",
    rootId: "552",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "08/31/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Gloster",
    status: "New",
    imagePath:
      "/n/cw/ec/129689/gloster-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14219,
  },
  {
    modelId: 1360,
    modelName: "D-Max",
    maskingName: "d-max",
    rootId: "441",
    makeId: 61,
    makeName: "Isuzu",
    makeMaskingName: "isuzu",
    launchedOn: "05/10/2021 00:00:00",
    discontinuationDate: "",
    rootName: "D-Max V-Cross",
    status: "New",
    imagePath: "/n/cw/ec/48082/d-max-exterior-right-side-view-2.jpeg?isig=0",
    versionId: 13249,
  },
  {
    modelId: 1248,
    modelName: "911",
    maskingName: "911",
    rootId: "25",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "04/17/2019 00:00:00",
    discontinuationDate: "",
    rootName: "911",
    status: "New",
    imagePath:
      "/cw/ec/39232/Porsche-992-911-Right-Front-Three-Quarter-154380.jpg?wm=0",
    versionId: 15515,
  },
  {
    modelId: 1803,
    modelName: "M4 Competition",
    maskingName: "m4-competition",
    rootId: "358",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "02/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "M4",
    status: "New",
    imagePath:
      "/n/cw/ec/111981/m4-competition-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13369,
  },
  {
    modelId: 1431,
    modelName: "F-Pace",
    maskingName: "f-pace",
    rootId: "410",
    makeId: 44,
    makeName: "Jaguar",
    makeMaskingName: "jaguar",
    launchedOn: "06/10/2021 00:00:00",
    discontinuationDate: "",
    rootName: "F-Pace",
    status: "New",
    imagePath:
      "/n/cw/ec/56265/f-pace-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 15567,
  },
  {
    modelId: 1362,
    modelName: "Kodiaq",
    maskingName: "kodiaq",
    rootId: "449",
    makeId: 15,
    makeName: "Skoda",
    makeMaskingName: "skoda",
    launchedOn: "01/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Kodiaq",
    status: "New",
    imagePath:
      "/n/cw/ec/49051/kodiaq-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 12769,
  },
  {
    modelId: 1819,
    modelName: "EV6",
    maskingName: "ev6",
    rootId: "685",
    makeId: 70,
    makeName: "Kia",
    makeMaskingName: "kia",
    launchedOn: "06/02/2022 00:00:00",
    discontinuationDate: "",
    rootName: "EV6",
    status: "New",
    imagePath:
      "/n/cw/ec/114971/ev6-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 10165,
  },
  {
    modelId: 1113,
    modelName: "Q3",
    maskingName: "q3",
    rootId: "232",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "08/30/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Q3",
    status: "New",
    imagePath:
      "/n/cw/ec/28379/q3-exterior-right-front-three-quarter-93481.jpeg?isig=0",
    versionId: 15399,
  },
  {
    modelId: 1873,
    modelName: "Range Rover Sport",
    maskingName: "range-rover-sport",
    rootId: "240",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "05/19/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Range Rover Sport",
    status: "New",
    imagePath:
      "/n/cw/ec/122451/range-rover-sport-exterior-right-front-three-quarter-20.jpeg?isig=0",
    versionId: 10181,
  },
  {
    modelId: 1348,
    modelName: "Meridian",
    maskingName: "meridian",
    rootId: "586",
    makeId: 43,
    makeName: "Jeep",
    makeMaskingName: "jeep",
    launchedOn: "05/19/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Meridian",
    status: "New",
    imagePath:
      "/n/cw/ec/47139/meridian-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 12935,
  },
  {
    modelId: 2061,
    modelName: "XC60",
    maskingName: "xc60",
    rootId: "319",
    makeId: 37,
    makeName: "Volvo",
    makeMaskingName: "volvo",
    launchedOn: "09/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XC60",
    status: "New",
    imagePath:
      "/n/cw/ec/131131/xc60-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15417,
  },
  {
    modelId: 2737,
    modelName: "AMG GLE Coupe",
    maskingName: "amg-gle-coupe",
    rootId: "602",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "01/31/2024 00:00:00",
    discontinuationDate: "",
    rootName: "GLE Coupe",
    status: "New",
    imagePath:
      "/n/cw/ec/169185/amg-gle-coupe-facelift-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 16359,
  },
  {
    modelId: 2019,
    modelName: "Atto 3",
    maskingName: "atto-3",
    rootId: "725",
    makeId: 111,
    makeName: "BYD",
    makeMaskingName: "byd",
    launchedOn: "11/14/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Atto 3",
    status: "New",
    imagePath:
      "/n/cw/ec/130183/atto-3-exterior-right-front-three-quarter-102.jpeg?isig=0",
    versionId: 10881,
  },
  {
    modelId: 1785,
    modelName: "Ioniq 5",
    maskingName: "ioniq-5",
    rootId: "683",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "01/11/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Ioniq 5",
    status: "New",
    imagePath:
      "/n/cw/ec/110289/ioniq-5-exterior-right-front-three-quarter-95.jpeg?isig=0",
    versionId: 11373,
  },
  {
    modelId: 2617,
    modelName: "i20 N Line",
    maskingName: "i20-n-line",
    rootId: "649",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "09/22/2023 00:00:00",
    discontinuationDate: "",
    rootName: "i20 N Line",
    status: "New",
    imagePath:
      "/n/cw/ec/158139/i20-n-line-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15163,
  },
  {
    modelId: 1405,
    modelName: "Tiguan",
    maskingName: "tiguan",
    rootId: "425",
    makeId: 20,
    makeName: "Volkswagen",
    makeMaskingName: "volkswagen",
    launchedOn: "12/07/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Tiguan",
    status: "New",
    imagePath:
      "/n/cw/ec/53123/tiguan-exterior-right-front-three-quarter-4.jpeg",
    versionId: 12745,
  },
  {
    modelId: 2163,
    modelName: "M340i",
    maskingName: "m340i",
    rootId: "14",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "12/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "3-Series",
    status: "New",
    imagePath:
      "/n/cw/ec/135697/m340i-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13367,
  },
  {
    modelId: 1791,
    modelName: "ZS EV",
    maskingName: "zs-ev",
    rootId: "536",
    makeId: 72,
    makeName: "MG",
    makeMaskingName: "mg",
    launchedOn: "03/07/2022 00:00:00",
    discontinuationDate: "",
    rootName: "ZS EV",
    status: "New",
    imagePath:
      "/n/cw/ec/110437/zs-ev-exterior-right-front-three-quarter-69.jpeg?isig=0",
    versionId: 16373,
  },
  {
    modelId: 2057,
    modelName: "XC90",
    maskingName: "xc90",
    rootId: "320",
    makeId: 37,
    makeName: "Volvo",
    makeMaskingName: "volvo",
    launchedOn: "09/21/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XC90",
    status: "New",
    imagePath:
      "/n/cw/ec/131135/xc90-exterior-right-front-three-quarter-106.jpeg?isig=0",
    versionId: 15419,
  },
  {
    modelId: 2709,
    modelName: "GLS",
    maskingName: "gls",
    rootId: "400",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "01/08/2024 00:00:00",
    discontinuationDate: "",
    rootName: "GLS",
    status: "New",
    imagePath:
      "/n/cw/ec/167373/gls-facelift-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15995,
  },
  {
    modelId: 2673,
    modelName: "Revuelto",
    maskingName: "revuelto",
    rootId: "2511",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "12/06/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Revuelto",
    status: "New",
    imagePath:
      "/n/cw/ec/164543/revuelto-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15891,
  },
  {
    modelId: 1253,
    modelName: "A6",
    maskingName: "a6",
    rootId: "28",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "10/24/2019 00:00:00",
    discontinuationDate: "",
    rootName: "A6",
    status: "New",
    imagePath:
      "/n/cw/ec/39472/a6-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 6625,
  },
  {
    modelId: 1363,
    modelName: "Gurkha",
    maskingName: "gurkha",
    rootId: "159",
    makeId: 50,
    makeName: "Force Motors",
    makeMaskingName: "force-motors",
    launchedOn: "09/27/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Gurkha",
    status: "New",
    imagePath:
      "/n/cw/ec/49096/gurkha-new-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15555,
  },
  {
    modelId: 827,
    modelName: "Huracan Evo",
    maskingName: "huracan-evo",
    rootId: "367",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "01/01/2014 00:00:00",
    discontinuationDate: "",
    rootName: "Huracan",
    status: "New",
    imagePath:
      "/n/cw/ec/14054/huracan-evo-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 6893,
  },
  {
    modelId: 2553,
    modelName: "Vellfire",
    maskingName: "vellfire",
    rootId: "544",
    makeId: 17,
    makeName: "Toyota",
    makeMaskingName: "toyota",
    launchedOn: "08/03/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Vellfire",
    status: "New",
    imagePath:
      "/n/cw/ec/154483/vellfire-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14561,
  },
  {
    modelId: 1603,
    modelName: "Macan",
    maskingName: "macan",
    rootId: "357",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "11/12/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Macan",
    status: "New",
    imagePath:
      "/n/cw/ec/99421/macan-exterior-right-front-three-quarter-9.jpeg?isig=0",
    versionId: 15483,
  },
  {
    modelId: 1351,
    modelName: "M8",
    maskingName: "m8",
    rootId: "589",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "05/08/2020 00:00:00",
    discontinuationDate: "",
    rootName: "M8",
    status: "New",
    imagePath:
      "/n/cw/ec/47278/m8-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13377,
  },
  {
    modelId: 1193,
    modelName: "ES",
    maskingName: "es",
    rootId: "475",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "07/20/2018 00:00:00",
    discontinuationDate: "",
    rootName: "ES",
    status: "New",
    imagePath:
      "/n/cw/ec/35351/es-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 8877,
  },
  {
    modelId: 1354,
    modelName: "E-Class",
    maskingName: "e-class",
    rootId: "110",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "03/16/2021 00:00:00",
    discontinuationDate: "",
    rootName: "E-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/47336/e-class-exterior-right-front-three-quarter-27.jpeg?isig=0",
    versionId: 15679,
  },
  {
    modelId: 1433,
    modelName: "6 Series GT",
    maskingName: "6-series-gt",
    rootId: "497",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "04/08/2021 00:00:00",
    discontinuationDate: "",
    rootName: "6-Series GT",
    status: "New",
    imagePath:
      "/n/cw/ec/56433/6-series-gt-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13363,
  },
  {
    modelId: 2533,
    modelName: "X5",
    maskingName: "x5",
    rootId: "317",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "07/14/2023 00:00:00",
    discontinuationDate: "",
    rootName: "X5",
    status: "New",
    imagePath:
      "/n/cw/ec/152681/x5-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 14499,
  },
  {
    modelId: 2161,
    modelName: "XM",
    maskingName: "xm",
    rootId: "755",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "12/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XM",
    status: "New",
    imagePath:
      "/n/cw/ec/135681/xm-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13391,
  },
  {
    modelId: 1132,
    modelName: "Phantom",
    maskingName: "phantom",
    rootId: "226",
    makeId: 25,
    makeName: "Rolls-Royce",
    makeMaskingName: "rolls-royce",
    launchedOn: "08/28/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Phantom",
    status: "New",
    imagePath:
      "/n/cw/ec/30181/phantom-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 7406,
  },
  {
    modelId: 2527,
    modelName: "GLC",
    maskingName: "glc",
    rootId: "426",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "08/09/2023 00:00:00",
    discontinuationDate: "",
    rootName: "GLC",
    status: "New",
    imagePath:
      "/n/cw/ec/150705/glc-exterior-right-front-three-quarter-94.jpeg?isig=0",
    versionId: 14579,
  },
  {
    modelId: 2647,
    modelName: "GLE",
    maskingName: "gle",
    rootId: "397",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "11/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "GLE",
    status: "New",
    imagePath:
      "/n/cw/ec/163317/gle-facelift-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15751,
  },
  {
    modelId: 1160,
    modelName: "Cayenne",
    maskingName: "cayenne",
    rootId: "63",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "10/17/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Cayenne",
    status: "New",
    imagePath:
      "/n/cw/ec/32951/cayenne-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15499,
  },
  {
    modelId: 1731,
    modelName: "Tucson",
    maskingName: "tucson",
    rootId: "421",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "08/10/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Tucson",
    status: "New",
    imagePath:
      "/n/cw/ec/106821/tucson-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 14701,
  },
  {
    modelId: 1451,
    modelName: "Maybach GLS",
    maskingName: "maybach-gls",
    rootId: "629",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "06/08/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Maybach GLS",
    status: "New",
    imagePath:
      "/n/cw/ec/95489/maybach-gls-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 15705,
  },
  {
    modelId: 1346,
    modelName: "e-tron GT",
    maskingName: "e-tron-gt",
    rootId: "532",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "09/22/2021 00:00:00",
    discontinuationDate: "",
    rootName: "e-tron",
    status: "New",
    imagePath:
      "/n/cw/ec/47073/e-tron-gt-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 8751,
  },
  {
    modelId: 1413,
    modelName: "Urus Performante",
    maskingName: "urus-performante",
    rootId: "735",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "11/24/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Urus Performante",
    status: "New",
    imagePath:
      "/n/cw/ec/53859/urus-performante-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 8973,
  },
  {
    modelId: 2109,
    modelName: "Grand Cherokee",
    maskingName: "grand-cherokee",
    rootId: "71",
    makeId: 43,
    makeName: "Jeep",
    makeMaskingName: "jeep",
    launchedOn: "11/17/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Cherokee",
    status: "New",
    imagePath:
      "/n/cw/ec/132711/grand-cherokee-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 11223,
  },
  {
    modelId: 2517,
    modelName: "M2",
    maskingName: "m2",
    rootId: "522",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "06/08/2023 00:00:00",
    discontinuationDate: "",
    rootName: "M2",
    status: "New",
    imagePath:
      "/n/cw/ec/150125/m2-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14337,
  },
  {
    modelId: 2377,
    modelName: "City Hybrid eHEV",
    maskingName: "city-hybrid",
    rootId: "687",
    makeId: 7,
    makeName: "Honda",
    makeMaskingName: "honda",
    launchedOn: "03/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "City eHEV",
    status: "New",
    imagePath:
      "/n/cw/ec/143275/city-hybrid-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 12341,
  },
  {
    modelId: 1797,
    modelName: "X3",
    maskingName: "x3",
    rootId: "316",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/20/2022 00:00:00",
    discontinuationDate: "",
    rootName: "X3",
    status: "New",
    imagePath:
      "/n/cw/ec/110503/x3-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 13403,
  },
  {
    modelId: 2729,
    modelName: "Spectre",
    maskingName: "spectre",
    rootId: "2521",
    makeId: 25,
    makeName: "Rolls-Royce",
    makeMaskingName: "rolls-royce",
    launchedOn: "01/19/2024 00:00:00",
    discontinuationDate: "",
    rootName: "Spectre",
    status: "New",
    imagePath:
      "/n/cw/ec/168715/spectre-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 16311,
  },
  {
    modelId: 1382,
    modelName: "XC40 Recharge",
    maskingName: "xc40-recharge",
    rootId: "498",
    makeId: 37,
    makeName: "Volvo",
    makeMaskingName: "volvo",
    launchedOn: "07/26/2022 00:00:00",
    discontinuationDate: "",
    rootName: "XC40",
    status: "New",
    imagePath:
      "/n/cw/ec/51766/xc40-recharge-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 9873,
  },
  {
    modelId: 1358,
    modelName: "S-Class",
    maskingName: "s-class",
    rootId: "265",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "06/17/2021 00:00:00",
    discontinuationDate: "",
    rootName: "S-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/48067/s-class-exterior-right-front-three-quarter-9.jpeg?isig=0",
    versionId: 15711,
  },
  {
    modelId: 1601,
    modelName: "Tiago NRG",
    maskingName: "tiago-nrg",
    rootId: "377",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "08/04/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Tiago",
    status: "New",
    imagePath:
      "/n/cw/ec/99113/tiago-nrg-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13805,
  },
  {
    modelId: 2315,
    modelName: "Q3 Sportback",
    maskingName: "q3-sportback",
    rootId: "232",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "02/13/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Q3",
    status: "New",
    imagePath:
      "/n/cw/ec/141373/q3-sportback-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 11997,
  },
  {
    modelId: 1326,
    modelName: "GLC Coupe",
    maskingName: "glc-coupe",
    rootId: "492",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "03/03/2020 00:00:00",
    discontinuationDate: "",
    rootName: "GLC Coupe",
    status: "New",
    imagePath:
      "/n/cw/ec/45477/mercedesbenz-glc-coupe-right-front-three-quarter1.jpeg",
    versionId: 15693,
  },
  {
    modelId: 2189,
    modelName: "AMG E53 Cabriolet",
    maskingName: "amg-e53-cabriolet",
    rootId: "761",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "01/06/2023 00:00:00",
    discontinuationDate: "",
    rootName: "AMG E53 Cabriolet",
    status: "New",
    imagePath:
      "/n/cw/ec/137541/amg-e53-cabriolet-exterior-right-front-three-quarter-8.jpeg?isig=0",
    versionId: 15639,
  },
  {
    modelId: 1182,
    modelName: "Countryman",
    maskingName: "countryman",
    rootId: "92",
    makeId: 51,
    makeName: "MINI",
    makeMaskingName: "mini",
    launchedOn: "05/03/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Countryman",
    status: "New",
    imagePath:
      "/n/cw/ec/34290/countryman-exterior-right-front-three-quarter-4.jpeg",
    versionId: 8023,
  },
  {
    modelId: 1359,
    modelName: "MU-X",
    maskingName: "mu-x",
    rootId: "424",
    makeId: 61,
    makeName: "Isuzu",
    makeMaskingName: "isuzu",
    launchedOn: "05/10/2021 00:00:00",
    discontinuationDate: "",
    rootName: "MU-X",
    status: "New",
    imagePath:
      "/n/cw/ec/48084/mu-x-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 13245,
  },
  {
    modelId: 2197,
    modelName: "LX",
    maskingName: "lx",
    rootId: "191",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "12/23/2022 00:00:00",
    discontinuationDate: "",
    rootName: "LX",
    status: "New",
    imagePath:
      "/n/cw/ec/137979/lx-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 11375,
  },
  {
    modelId: 1041,
    modelName: "718",
    maskingName: "718",
    rootId: "450",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "05/17/2017 00:00:00",
    discontinuationDate: "",
    rootName: "718",
    status: "New",
    imagePath:
      "/n/cw/ec/24421/718-exterior-right-front-three-quarter-90912.jpeg?isig=0",
    versionId: 15421,
  },
  {
    modelId: 2357,
    modelName: "Venue N Line",
    maskingName: "venue-n-line",
    rootId: "515",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "02/14/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Venue",
    status: "New",
    imagePath:
      "/n/cw/ec/142677/venue-n-line-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15813,
  },
  {
    modelId: 2651,
    modelName: "X4 M40i",
    maskingName: "x4",
    rootId: "526",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "10/26/2023 00:00:00",
    discontinuationDate: "",
    rootName: "X4",
    status: "New",
    imagePath:
      "/n/cw/ec/163337/x4-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15627,
  },
  {
    modelId: 1020,
    modelName: "Q7",
    maskingName: "q7",
    rootId: "234",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "02/03/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Q7",
    status: "New",
    imagePath:
      "/n/cw/ec/22803/audi-q7-facelift-right-front-three-quarter4.jpeg",
    versionId: 9255,
  },
  {
    modelId: 2111,
    modelName: "eC3",
    maskingName: "ec3",
    rootId: "747",
    makeId: 74,
    makeName: "Citroen",
    makeMaskingName: "citroen",
    launchedOn: "02/27/2023 00:00:00",
    discontinuationDate: "",
    rootName: "eC3",
    status: "New",
    imagePath:
      "/n/cw/ec/132771/ec3-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 11569,
  },
  {
    modelId: 1254,
    modelName: "I-Pace",
    maskingName: "i-pace",
    rootId: "537",
    makeId: 44,
    makeName: "Jaguar",
    makeMaskingName: "jaguar",
    launchedOn: "03/23/2021 00:00:00",
    discontinuationDate: "",
    rootName: "I-Pace",
    status: "New",
    imagePath:
      "/n/cw/ec/39480/i-pace-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 8131,
  },
  {
    modelId: 2559,
    modelName: "296 GTB",
    maskingName: "296-gtb",
    rootId: "851",
    makeId: 33,
    makeName: "Ferrari",
    makeMaskingName: "ferrari",
    launchedOn: "08/26/2022 00:00:00",
    discontinuationDate: "",
    rootName: "296 GTB",
    status: "New",
    imagePath:
      "/n/cw/ec/154779/296-gtb-exterior-right-front-three-quarter-23.jpeg?isig=0",
    versionId: 14633,
  },
  {
    modelId: 1045,
    modelName: "Discovery",
    maskingName: "discovery",
    rootId: "106",
    makeId: 23,
    makeName: "Land Rover",
    makeMaskingName: "land-rover",
    launchedOn: "08/09/2017 00:00:00",
    discontinuationDate: "",
    rootName: "Discovery",
    status: "New",
    imagePath: "/cw/ec/24806/Land-Rover-Discovery-Exterior-104355.jpg?wm=0",
    versionId: 15593,
  },
  {
    modelId: 1449,
    modelName: "720S",
    maskingName: "720s",
    rootId: "627",
    makeId: 77,
    makeName: "McLaren",
    makeMaskingName: "mclaren",
    launchedOn: "06/11/2021 00:00:00",
    discontinuationDate: "",
    rootName: "720S",
    status: "New",
    imagePath:
      "/n/cw/ec/95143/720s-coupe-exterior-right-front-three-quarter.jpeg",
    versionId: 8303,
  },
  {
    modelId: 1453,
    modelName: "Huracan Evo Spyder",
    maskingName: "huracan-evo-spyder",
    rootId: "631",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "07/19/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Huracan Evo Spyder",
    status: "New",
    imagePath:
      "/n/cw/ec/95475/huracan-evo-spyder-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 8293,
  },
  {
    modelId: 2015,
    modelName: "e6",
    maskingName: "e6",
    rootId: "723",
    makeId: 111,
    makeName: "BYD",
    makeMaskingName: "byd",
    launchedOn: "08/27/2022 00:00:00",
    discontinuationDate: "",
    rootName: "e6",
    status: "New",
    imagePath:
      "/n/cw/ec/129901/e6-exterior-right-front-three-quarter-48.jpeg?isig=0",
    versionId: 10851,
  },
  {
    modelId: 1409,
    modelName: "Q5",
    maskingName: "q5",
    rootId: "233",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "11/23/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Q5",
    status: "New",
    imagePath:
      "/n/cw/ec/53591/q5-exterior-right-front-three-quarter-36.jpeg?isig=0",
    versionId: 9117,
  },
  {
    modelId: 1378,
    modelName: "S5 Sportback",
    maskingName: "s5-sportback",
    rootId: "600",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "03/22/2021 00:00:00",
    discontinuationDate: "",
    rootName: "S5 Sportback",
    status: "New",
    imagePath:
      "/n/cw/ec/51378/s5-sportback-exterior-right-front-three-quarter-5.jpeg",
    versionId: 8123,
  },
  {
    modelId: 1443,
    modelName: "AMG A35",
    maskingName: "amg-a35",
    rootId: "623",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "03/25/2021 00:00:00",
    discontinuationDate: "",
    rootName: "AMG A35 Limousine",
    status: "New",
    imagePath:
      "/n/cw/ec/94041/amg-a35-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 15633,
  },
  {
    modelId: 1187,
    modelName: "Q8",
    maskingName: "q8",
    rootId: "512",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "01/15/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Q8",
    status: "New",
    imagePath:
      "/n/cw/ec/34470/q8-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 7595,
  },
  {
    modelId: 1365,
    modelName: "Marazzo",
    maskingName: "marazzo",
    rootId: "471",
    makeId: 9,
    makeName: "Mahindra",
    makeMaskingName: "mahindra",
    launchedOn: "08/25/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Marazzo",
    status: "New",
    imagePath:
      "/n/cw/ec/49114/marazzo-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 14375,
  },
  {
    modelId: 2195,
    modelName: "i7",
    maskingName: "i7",
    rootId: "765",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "01/07/2023 00:00:00",
    discontinuationDate: "",
    rootName: "i7",
    status: "New",
    imagePath:
      "/n/cw/ec/137875/i7-exterior-right-front-three-quarter-8.jpeg?isig=0",
    versionId: 15955,
  },
  {
    modelId: 2523,
    modelName: "C40 Recharge",
    maskingName: "c40-recharge",
    rootId: "843",
    makeId: 37,
    makeName: "Volvo",
    makeMaskingName: "volvo",
    launchedOn: "09/04/2023 00:00:00",
    discontinuationDate: "",
    rootName: "C40 Recharge",
    status: "New",
    imagePath:
      "/n/cw/ec/150611/c40-recharge-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 14757,
  },
  {
    modelId: 1175,
    modelName: "Ghibli",
    maskingName: "ghibli",
    rootId: "403",
    makeId: 36,
    makeName: "Maserati",
    makeMaskingName: "maserati",
    launchedOn: "03/16/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Ghibli",
    status: "New",
    imagePath:
      "/n/cw/ec/33688/ghibli-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 9135,
  },
  {
    modelId: 2133,
    modelName: "GLB",
    maskingName: "glb",
    rootId: "559",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "12/02/2022 00:00:00",
    discontinuationDate: "",
    rootName: "GLB",
    status: "New",
    imagePath:
      "/n/cw/ec/134297/glb-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15687,
  },
  {
    modelId: 2499,
    modelName: "AMG SL55 Roadster",
    maskingName: "amg-sl55-roadster",
    rootId: "831",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "06/22/2023 00:00:00",
    discontinuationDate: "",
    rootName: "AMG SL55 Roadster",
    status: "New",
    imagePath:
      "/n/cw/ec/148919/amg-sl55-roadster-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14391,
  },
  {
    modelId: 1813,
    modelName: "NX",
    maskingName: "nx",
    rootId: "491",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "03/09/2022 00:00:00",
    discontinuationDate: "",
    rootName: "NX",
    status: "New",
    imagePath:
      "/n/cw/ec/113023/nx-2022-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 9603,
  },
  {
    modelId: 1771,
    modelName: "i4",
    maskingName: "i4",
    rootId: "679",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "05/26/2022 00:00:00",
    discontinuationDate: "",
    rootName: "i4",
    status: "New",
    imagePath:
      "/n/cw/ec/109123/i4-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 15195,
  },
  {
    modelId: 2017,
    modelName: "C5 Aircross",
    maskingName: "c5-aircross",
    rootId: "527",
    makeId: 74,
    makeName: "Citroen",
    makeMaskingName: "citroen",
    launchedOn: "09/08/2022 00:00:00",
    discontinuationDate: "",
    rootName: "C5",
    status: "New",
    imagePath:
      "/n/cw/ec/129909/c5-aircross-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 10859,
  },
  {
    modelId: 1423,
    modelName: "Bentayga",
    maskingName: "bentayga",
    rootId: "440",
    makeId: 22,
    makeName: "Bentley",
    makeMaskingName: "bentley",
    launchedOn: "03/16/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Bentayga",
    status: "New",
    imagePath:
      "/n/cw/ec/55335/bentayga-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 8113,
  },
  {
    modelId: 2681,
    modelName: "Panamera",
    maskingName: "panamera",
    rootId: "223",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "11/29/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Panamera",
    status: "New",
    imagePath:
      "/n/cw/ec/165641/panamera-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 15889,
  },
  {
    modelId: 1125,
    modelName: "Kona Electric",
    maskingName: "kona-electric",
    rootId: "484",
    makeId: 8,
    makeName: "Hyundai",
    makeMaskingName: "hyundai",
    launchedOn: "07/09/2019 00:00:00",
    discontinuationDate: "",
    rootName: "Kona Electric",
    status: "New",
    imagePath:
      "/n/cw/ec/29580/kona-electric-exterior-right-front-three-quarter-162254.jpeg?isig=0",
    versionId: 6445,
  },
  {
    modelId: 1308,
    modelName: "LC 500h",
    maskingName: "lc-500h",
    rootId: "561",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "01/31/2020 00:00:00",
    discontinuationDate: "",
    rootName: "LC 500h",
    status: "New",
    imagePath: "/n/cw/ec/44615/lexus-lc-500h-right-front-three-quarter10.jpeg",
    versionId: 6912,
  },
  {
    modelId: 2629,
    modelName: "DB12",
    maskingName: "db12",
    rootId: "2497",
    makeId: 49,
    makeName: "Aston Martin",
    makeMaskingName: "aston-martin",
    launchedOn: "09/29/2023 00:00:00",
    discontinuationDate: "",
    rootName: "DB12",
    status: "New",
    imagePath:
      "/n/cw/ec/158905/db12-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 15211,
  },
  {
    modelId: 2467,
    modelName: "AMG GT 63 S E Performance",
    maskingName: "amg-gt-63-s-e-performance",
    rootId: "825",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "04/11/2023 00:00:00",
    discontinuationDate: "",
    rootName: "AMG GT 63 SE Performance",
    status: "New",
    imagePath:
      "/n/cw/ec/145977/amg-gt-63-s-e-performance-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 15655,
  },
  {
    modelId: 2715,
    modelName: "750S",
    maskingName: "750s",
    rootId: "2515",
    makeId: 77,
    makeName: "McLaren",
    makeMaskingName: "mclaren",
    launchedOn: "01/12/2024 00:00:00",
    discontinuationDate: "",
    rootName: "750S",
    status: "New",
    imagePath:
      "/n/cw/ec/167883/750s-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 16199,
  },
  {
    modelId: 1315,
    modelName: "Taycan",
    maskingName: "taycan",
    rootId: "569",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "11/12/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Taycan",
    status: "New",
    imagePath:
      "/n/cw/ec/45063/taycan-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 15533,
  },
  {
    modelId: 2473,
    modelName: "Urus S",
    maskingName: "urus-s",
    rootId: "493",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "04/13/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Urus",
    status: "New",
    imagePath:
      "/n/cw/ec/146547/urus-s-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 13305,
  },
  {
    modelId: 1445,
    modelName: "AMG GLA35",
    maskingName: "amg-gla35",
    rootId: "563",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "05/25/2021 00:00:00",
    discontinuationDate: "",
    rootName: "AMG GLA 35",
    status: "New",
    imagePath:
      "/n/cw/ec/94279/amg-gla35-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15643,
  },
  {
    modelId: 1763,
    modelName: "Cooper SE",
    maskingName: "cooper-se",
    rootId: "675",
    makeId: 51,
    makeName: "MINI",
    makeMaskingName: "mini",
    launchedOn: "02/24/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Cooper SE",
    status: "New",
    imagePath:
      "/n/cw/ec/108863/cooper-se-exterior-right-front-three-quarter-39.jpeg?isig=0",
    versionId: 9541,
  },
  {
    modelId: 2299,
    modelName: "iX1",
    maskingName: "ix1",
    rootId: "807",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "09/28/2023 00:00:00",
    discontinuationDate: "",
    rootName: "iX1",
    status: "New",
    imagePath:
      "/n/cw/ec/140585/ix1-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15201,
  },
  {
    modelId: 2157,
    modelName: "Trax Cruiser",
    maskingName: "trax-cruiser",
    rootId: "753",
    makeId: 50,
    makeName: "Force Motors",
    makeMaskingName: "force-motors",
    launchedOn: "09/10/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Trax Cruiser",
    status: "New",
    imagePath:
      "/n/cw/ec/135589/trax-cruiser-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15557,
  },
  {
    modelId: 1184,
    modelName: "Cullinan",
    maskingName: "cullinan",
    rootId: "511",
    makeId: 25,
    makeName: "Rolls-Royce",
    makeMaskingName: "rolls-royce",
    launchedOn: "12/05/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Cullinan",
    status: "New",
    imagePath: "/cw/ec/34427/RollsRoyce-Cullinan-Exterior-158729.jpg?wm=0",
    versionId: 7402,
  },
  {
    modelId: 1367,
    modelName: "RS Q8",
    maskingName: "rs-q8",
    rootId: "512",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "08/27/2020 00:00:00",
    discontinuationDate: "",
    rootName: "Q8",
    status: "New",
    imagePath:
      "/n/cw/ec/49294/rs-q8-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 7504,
  },
  {
    modelId: 1593,
    modelName: "AMG E53",
    maskingName: "amg-e53",
    rootId: "110",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "07/15/2021 00:00:00",
    discontinuationDate: "",
    rootName: "E-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/98397/amg-e53-exterior-right-front-three-quarter-2.jpeg",
    versionId: 15637,
  },
  {
    modelId: 2167,
    modelName: "Tigor EV",
    maskingName: "tigor-ev",
    rootId: "554",
    makeId: 16,
    makeName: "Tata",
    makeMaskingName: "tata",
    launchedOn: "11/23/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Tigor EV",
    status: "New",
    imagePath:
      "/n/cw/ec/135723/tigor-ev-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 11281,
  },
  {
    modelId: 1889,
    modelName: "A8 L",
    maskingName: "a8-l",
    rootId: "30",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "07/12/2022 00:00:00",
    discontinuationDate: "",
    rootName: "A8",
    status: "New",
    imagePath:
      "/n/cw/ec/124141/a8-l-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 10485,
  },
  {
    modelId: 1376,
    modelName: "AMG GLC43 Coupe",
    maskingName: "amg-glc43-coupe",
    rootId: "598",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "11/03/2020 00:00:00",
    discontinuationDate: "",
    rootName: "AMG GLC 43 Coupe",
    status: "New",
    imagePath:
      "/n/cw/ec/50924/amg-glc43-coupe-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15645,
  },
  {
    modelId: 1461,
    modelName: "Huracan STO",
    maskingName: "huracan-sto",
    rootId: "639",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "07/15/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Huracan STO",
    status: "New",
    imagePath:
      "/n/cw/ec/97705/huracan-sto-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 8445,
  },
  {
    modelId: 1591,
    modelName: "Roma",
    maskingName: "roma",
    rootId: "643",
    makeId: 33,
    makeName: "Ferrari",
    makeMaskingName: "ferrari",
    launchedOn: "07/08/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Roma",
    status: "New",
    imagePath:
      "/n/cw/ec/97963/roma-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 8419,
  },
  {
    modelId: 1455,
    modelName: "GT",
    maskingName: "gt",
    rootId: "633",
    makeId: 77,
    makeName: "McLaren",
    makeMaskingName: "mclaren",
    launchedOn: "06/11/2021 00:00:00",
    discontinuationDate: "",
    rootName: "GT",
    status: "New",
    imagePath: "/n/cw/ec/95701/gt-exterior-right-front-three-quarter-2.jpeg",
    versionId: 8307,
  },
  {
    modelId: 2741,
    modelName: "Macan Turbo EV",
    maskingName: "macan-turbo-ev",
    rootId: "357",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "01/29/2024 00:00:00",
    discontinuationDate: "",
    rootName: "Macan",
    status: "New",
    imagePath:
      "/n/cw/ec/169989/macan-turbo-ev-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 16369,
  },
  {
    modelId: 1943,
    modelName: "Eletre",
    maskingName: "eletre",
    rootId: "717",
    makeId: 123,
    makeName: "Lotus",
    makeMaskingName: "lotus",
    launchedOn: "11/09/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Eletre",
    status: "New",
    imagePath:
      "/n/cw/ec/164919/eletre-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 10547,
  },
  {
    modelId: 1205,
    modelName: "Vantage",
    maskingName: "vantage",
    rootId: "302",
    makeId: 49,
    makeName: "Aston Martin",
    makeMaskingName: "aston-martin",
    launchedOn: "09/25/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Vantage",
    status: "New",
    imagePath:
      "/n/cw/ec/36225/vantage-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 7382,
  },
  {
    modelId: 1104,
    modelName: "LS",
    maskingName: "ls",
    rootId: "190",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "01/15/2018 00:00:00",
    discontinuationDate: "",
    rootName: "LS",
    status: "New",
    imagePath:
      "/n/cw/ec/28191/ls-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 7409,
  },
  {
    modelId: 2253,
    modelName: "RX",
    maskingName: "rx",
    rootId: "253",
    makeId: 34,
    makeName: "Lexus",
    makeMaskingName: "lexus",
    launchedOn: "04/19/2023 00:00:00",
    discontinuationDate: "",
    rootName: "RX",
    status: "New",
    imagePath:
      "/n/cw/ec/139465/rx-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 12775,
  },
  {
    modelId: 1368,
    modelName: "F8 Tributo",
    maskingName: "f8-tributo",
    rootId: "596",
    makeId: 33,
    makeName: "Ferrari",
    makeMaskingName: "ferrari",
    launchedOn: "08/06/2020 00:00:00",
    discontinuationDate: "",
    rootName: "F8 Tributo",
    status: "New",
    imagePath:
      "/n/cw/ec/49376/f8-tributo-exterior-right-front-three-quarter-12.jpeg?isig=0",
    versionId: 7459,
  },
  {
    modelId: 2041,
    modelName: "Huracan Tecnica",
    maskingName: "huracan-tecnica",
    rootId: "367",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "08/25/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Huracan",
    status: "New",
    imagePath:
      "/n/cw/ec/130671/huracan-tecnica-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 10903,
  },
  {
    modelId: 1611,
    modelName: "RS5",
    maskingName: "rs5",
    rootId: "508",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "08/09/2021 00:00:00",
    discontinuationDate: "",
    rootName: "RS5",
    status: "New",
    imagePath:
      "/n/cw/ec/100073/rs5-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 8535,
  },
  {
    modelId: 1051,
    modelName: "DB11",
    maskingName: "db11",
    rootId: "457",
    makeId: 49,
    makeName: "Aston Martin",
    makeMaskingName: "aston-martin",
    launchedOn: "01/01/2016 00:00:00",
    discontinuationDate: "",
    rootName: "DB11",
    status: "New",
    imagePath:
      "/cw/ec/25539/Aston-Martin-DB11-Right-Front-Three-Quarter-82872.jpg?wm=0",
    versionId: 7381,
  },
  {
    modelId: 969,
    modelName: "Wraith",
    maskingName: "wraith",
    rootId: "418",
    makeId: 25,
    makeName: "Rolls-Royce",
    makeMaskingName: "rolls-royce",
    launchedOn: "12/17/2015 00:00:00",
    discontinuationDate: "",
    rootName: "Wraith",
    status: "New",
    imagePath:
      "/n/cw/ec/21135/wraith-exterior-right-front-three-quarter-62430.jpeg?isig=0",
    versionId: 7407,
  },
  {
    modelId: 2475,
    modelName: "X3 M40i",
    maskingName: "x3-m40i",
    rootId: "827",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "05/11/2023 00:00:00",
    discontinuationDate: "",
    rootName: "X3 M40i",
    status: "New",
    imagePath:
      "/n/cw/ec/146751/x3-m40i-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14089,
  },
  {
    modelId: 924,
    modelName: "Quattroporte",
    maskingName: "quattroporte",
    rootId: "237",
    makeId: 36,
    makeName: "Maserati",
    makeMaskingName: "maserati",
    launchedOn: "07/15/2015 00:00:00",
    discontinuationDate: "",
    rootName: "Quattroporte",
    status: "New",
    imagePath:
      "/n/cw/ec/19429/quattroporte-exterior-right-front-three-quarter-149975.jpeg?isig=0",
    versionId: 9187,
  },
  {
    modelId: 2511,
    modelName: "AMG A45 S",
    maskingName: "amg-a45-s",
    rootId: "661",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "05/24/2023 00:00:00",
    discontinuationDate: "",
    rootName: "AMG A45 S",
    status: "New",
    imagePath:
      "/n/cw/ec/149523/amg-a45-s-exterior-right-front-three-quarter-7.jpeg?isig=0",
    versionId: 15635,
  },
  {
    modelId: 1380,
    modelName: "X5 M",
    maskingName: "x5-m",
    rootId: "601",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "11/26/2020 00:00:00",
    discontinuationDate: "",
    rootName: "X5 M",
    status: "New",
    imagePath:
      "/n/cw/ec/51529/x5-m-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 13379,
  },
  {
    modelId: 1316,
    modelName: "AMG GT 63 S 4MATIC Plus",
    maskingName: "amg-gt-63-s-4matic-plus",
    rootId: "570",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "02/05/2020 00:00:00",
    discontinuationDate: "",
    rootName: "AMG GT 63 S 4MATIC Plus",
    status: "New",
    imagePath:
      "/n/cw/ec/45126/amg-gt-63-s-4matic-plus-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15651,
  },
  {
    modelId: 1747,
    modelName: "Taycan Cross Turismo",
    maskingName: "taycan-cross-turismo",
    rootId: "667",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "11/12/2021 00:00:00",
    discontinuationDate: "",
    rootName: "Taycan Turismo",
    status: "New",
    imagePath:
      "/n/cw/ec/108081/taycan-cross-turismo-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 9147,
  },
  {
    modelId: 2135,
    modelName: "DBX",
    maskingName: "dbx",
    rootId: "655",
    makeId: 49,
    makeName: "Aston Martin",
    makeMaskingName: "aston-martin",
    launchedOn: "10/06/2022 00:00:00",
    discontinuationDate: "",
    rootName: "DBX",
    status: "New",
    imagePath:
      "/n/cw/ec/134427/dbx-exterior-right-front-three-quarter-7.png?isig=0",
    versionId: 11207,
  },
  {
    modelId: 1298,
    modelName: "Cayenne Coupe",
    maskingName: "cayenne-coupe",
    rootId: "729",
    makeId: 19,
    makeName: "Porsche",
    makeMaskingName: "porsche",
    launchedOn: "12/13/2019 00:00:00",
    discontinuationDate: "",
    rootName: "Cayenne Coupe",
    status: "New",
    imagePath:
      "/n/cw/ec/43728/cayenne-coupe-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15543,
  },
  {
    modelId: 1595,
    modelName: "AMG E63",
    maskingName: "amg-e63",
    rootId: "110",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "07/15/2021 00:00:00",
    discontinuationDate: "",
    rootName: "E-Class",
    status: "New",
    imagePath:
      "/n/cw/ec/98399/amg-e63-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 15641,
  },
  {
    modelId: 1749,
    modelName: "EQB",
    maskingName: "eqb",
    rootId: "669",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "12/02/2022 00:00:00",
    discontinuationDate: "",
    rootName: "EQB",
    status: "New",
    imagePath:
      "/n/cw/ec/108055/eqb-exterior-right-front-three-quarter-14.jpeg?isig=0",
    versionId: 11329,
  },
  {
    modelId: 1759,
    modelName: "iX",
    maskingName: "ix",
    rootId: "673",
    makeId: 1,
    makeName: "BMW",
    makeMaskingName: "bmw",
    launchedOn: "12/13/2021 00:00:00",
    discontinuationDate: "",
    rootName: "iX",
    status: "New",
    imagePath:
      "/n/cw/ec/108499/ix-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 9205,
  },
  {
    modelId: 2067,
    modelName: "EQS",
    maskingName: "eqs",
    rootId: "619",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "09/30/2022 00:00:00",
    discontinuationDate: "",
    rootName: "EQS",
    status: "New",
    imagePath:
      "/n/cw/ec/131249/eqs-exterior-right-front-three-quarter-6.jpeg?isig=0",
    versionId: 11099,
  },
  {
    modelId: 1090,
    modelName: "Levante",
    maskingName: "levante",
    rootId: "470",
    makeId: 36,
    makeName: "Maserati",
    makeMaskingName: "maserati",
    launchedOn: "01/29/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Levante",
    status: "New",
    imagePath:
      "/n/cw/ec/26924/levante-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 9179,
  },
  {
    modelId: 2649,
    modelName: "AMG C 43",
    maskingName: "amg-c-43",
    rootId: "2507",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "11/02/2023 00:00:00",
    discontinuationDate: "",
    rootName: "AMG C 43",
    status: "New",
    imagePath:
      "/n/cw/ec/163327/amg-c-43-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15761,
  },
  {
    modelId: 1437,
    modelName: "AMG EQS",
    maskingName: "amg-eqs",
    rootId: "619",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "08/24/2022 00:00:00",
    discontinuationDate: "",
    rootName: "EQS",
    status: "New",
    imagePath:
      "/n/cw/ec/58165/amg-eqs-exterior-right-front-three-quarter-60.jpeg?isig=0",
    versionId: 10764,
  },
  {
    modelId: 2543,
    modelName: "Q8 e-tron",
    maskingName: "q8-e-tron",
    rootId: "845",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "08/18/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Q8 e-tron",
    status: "New",
    imagePath:
      "/n/cw/ec/152943/q8-e-tron-exterior-right-front-three-quarter-5.jpeg?isig=0",
    versionId: 14727,
  },
  {
    modelId: 1206,
    modelName: "Portofino",
    maskingName: "portofino",
    rootId: "519",
    makeId: 33,
    makeName: "Ferrari",
    makeMaskingName: "ferrari",
    launchedOn: "09/28/2018 00:00:00",
    discontinuationDate: "",
    rootName: "Portofino",
    status: "New",
    imagePath:
      "/n/cw/ec/36258/portofino-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 9433,
  },
  {
    modelId: 2547,
    modelName: "Q8 Sportback e-tron",
    maskingName: "q8-sportback-e-tron",
    rootId: "847",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "08/18/2023 00:00:00",
    discontinuationDate: "",
    rootName: "Q8 e-tron Sportback",
    status: "New",
    imagePath:
      "/n/cw/ec/153789/q8-sportback-e-tron-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 14731,
  },
  {
    modelId: 1751,
    modelName: "EQE SUV",
    maskingName: "eqe-suv",
    rootId: "671",
    makeId: 11,
    makeName: "Mercedes-Benz",
    makeMaskingName: "mercedes-benz",
    launchedOn: "09/15/2023 00:00:00",
    discontinuationDate: "",
    rootName: "EQE SUV",
    status: "New",
    imagePath:
      "/n/cw/ec/108113/eqe-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 15091,
  },
  {
    modelId: 2583,
    modelName: "296 GTS",
    maskingName: "296-gts",
    rootId: "857",
    makeId: 33,
    makeName: "Ferrari",
    makeMaskingName: "ferrari",
    launchedOn: "05/23/2023 00:00:00",
    discontinuationDate: "",
    rootName: "296 GTS",
    status: "New",
    imagePath:
      "/n/cw/ec/155685/296-gts-exterior-right-front-three-quarter-4.jpeg?isig=0",
    versionId: 14755,
  },
  {
    modelId: 1769,
    modelName: "MC20",
    maskingName: "mc20",
    rootId: "677",
    makeId: 36,
    makeName: "Maserati",
    makeMaskingName: "maserati",
    launchedOn: "12/02/2021 00:00:00",
    discontinuationDate: "",
    rootName: "MC20",
    status: "New",
    imagePath:
      "/n/cw/ec/108971/mc20-exterior-right-front-three-quarter-2.jpeg?isig=0",
    versionId: 9225,
  },
  {
    modelId: 1033,
    modelName: "Dawn",
    maskingName: "dawn",
    rootId: "445",
    makeId: 25,
    makeName: "Rolls-Royce",
    makeMaskingName: "rolls-royce",
    launchedOn: "06/24/2016 00:00:00",
    discontinuationDate: "",
    rootName: "Dawn",
    status: "New",
    imagePath:
      "/n/cw/ec/23875/dawn-exterior-right-front-three-quarter-75145.jpeg?isig=0",
    versionId: 7403,
  },
  {
    modelId: 1242,
    modelName: "e-tron Sportback",
    maskingName: "e-tron-sportback",
    rootId: "532",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "07/22/2021 00:00:00",
    discontinuationDate: "",
    rootName: "e-tron",
    status: "New",
    imagePath:
      "/n/cw/ec/39045/e-tron-sportback-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 8425,
  },
  {
    modelId: 1243,
    modelName: "e-tron",
    maskingName: "e-tron",
    rootId: "532",
    makeId: 18,
    makeName: "Audi",
    makeMaskingName: "audi",
    launchedOn: "07/22/2021 00:00:00",
    discontinuationDate: "",
    rootName: "e-tron",
    status: "New",
    imagePath:
      "/n/cw/ec/39048/e-tron-exterior-right-front-three-quarter-3.jpeg?isig=0",
    versionId: 8421,
  },
  {
    modelId: 2645,
    modelName: "Huracan Sterrato",
    maskingName: "huracan-sterrato",
    rootId: "2505",
    makeId: 30,
    makeName: "Lamborghini",
    makeMaskingName: "lamborghini",
    launchedOn: "12/11/2022 00:00:00",
    discontinuationDate: "",
    rootName: "Huracan Sterrato",
    status: "New",
    imagePath:
      "/n/cw/ec/163239/huracan-sterrato-exterior-right-front-three-quarter.jpeg?isig=0",
    versionId: 15581,
  },
];

export default data;
